version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: db_mongodb
    ports:
      - '27017:27017'
    restart: on-failure
    volumes:
      - ./docker/mongodb/data:/data/db

  krakend:
    container_name: app_api_gateway
    restart: always
    build:
      context: ./docker/krakend
    ports:
      - 2007:8080
    volumes:
      - ./apps/krakend:/etc/krakend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: app_rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: on-failure
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  authentication-service:
    container_name: service_authentication
    restart: on-failure
    build:
      context: ./services/authentication-service
    volumes:
      - ./services/authentication-service/src:/app/src
    ports:
      - 4000:3000
    depends_on:
      - rabbitmq
      - mongodb
      - mysql

  email-service:
    container_name: service_email
    restart: on-failure
    build:
      context: ./services/email-service
    volumes:
      - ./services/email-service/src:/app/src
    ports:
      - 4001:3001
    depends_on:
      - rabbitmq

  course-service:
    container_name: service_course
    restart: on-failure
    build:
      context: ./services/course-service
    volumes:
      - ./services/course-service/src:/app/src
    ports:
      - 4002:3002
    depends_on:
      - mysql

  instructor-service:
    container_name: service_instructor
    restart: on-failure
    build:
      context: ./services/instructor-service
    volumes:
      - ./services/instructor-service/src:/app/src
    ports:
      - 4003:3003
    depends_on:
      - mongodb
      - authentication-service
